services:
  - type: web
    name: sselectric-vacation-system
    env: python
    buildCommand: |
      apt-get update -y
      apt-get install -y build-essential fonts-nanum fonts-noto-cjk libpango-1.0-0 libpangoft2-1.0-0
      pip install --upgrade pip
      pip install -r requirements-render.txt
      python3 create_admin.py
      python3 add_holidays.py
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 main:app
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: PYTHONIOENCODING
        value: "utf-8"
    autoDeploy: true